---
abstract: 'Pure Perl 65C02 simulator.'
author:
  - 'Andy Armstrong <andy@hexten.net>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-6502
provides:
  Acme::6502:
    file: lib/Acme/6502.pm
    version: 0.76
  Acme::6502::Tube:
    file: lib/Acme/6502/Tube.pm
    version: 0.76
requires:
  Term::ReadKey: 0
  Test::More: 0
  version: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Acme-6502
  license: http://dev.perl.org/licenses/
  repository: 'git://github.com/AndyA/Acme--6502.git (fetch)'
version: 0.76
