--- #YAML:1.0
name:                Acme-6502
version:             v0.0.6
abstract:            Pure Perl 65C02 simulator.
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Class::Std:                    0
    Class::Std::Slots:             0
    Term::ReadKey:                 0
    Test::More:                    0
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Andy Armstrong <andy@hexten.net>
